####  application-dev.yml

server:
  port: 8120


spring:
  profiles:
    active: dev   # 环境设置

  application:
    name: service-oss  # 服务名


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#logging:
#  level:
#    root: DEBUG
logging:
  config: classpath:logback-spring.xml


aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyid: LTAI5tJmoqDwMhPu168ovPCk
    keysecret: pYmC40StcjxDXvjEn3PrsJ5XqHKW28
    bucketName: edu-zaixian-avatar
